# Generated by Django 2.2.10 on 2020-11-13 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GolfPicks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=64)),
                ('player1', models.TextField(max_length=64)),
                ('player2', models.TextField(max_length=64)),
                ('player3', models.TextField(max_length=64)),
                ('player4', models.TextField(max_length=64)),
                ('winning_score', models.TextField(max_length=8)),
            ],
        ),
    ]
