version: '3.7'

services:
  web:
    build: ./frontend
    command: npm run serve
    volumes:
      - '.:/app'
    ports:
      - 8080:8080
    depends_on:
      - backend

  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/usr/src/backend/
    expose:
      - 8000
    ports:
      - 8000:8000
    env_file:
      - ./backend/.env.dev
    depends_on:
      - db

  db:
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=defaultPassword
      - POSTGRES_DB=backend

volumes:
  postgres_data:

