# Generated by Django 2.2.4 on 2019-08-30 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team', models.TextField(max_length=64)),
                ('away_team', models.TextField(max_length=64)),
                ('home_spread', models.FloatField()),
                ('away_spread', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.TextField(max_length=64)),
                ('nickname', models.TextField(max_length=64)),
            ],
        ),
    ]
