# Generated by Django 2.2.4 on 2019-08-30 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pickem', '0002_auto_20190830_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='away_spread',
        ),
        migrations.RemoveField(
            model_name='game',
            name='home_spread',
        ),
        migrations.AddField(
            model_name='game',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='week',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_away_team', to='pickem.Team'),
        ),
        migrations.AlterField(
            model_name='game',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_home_team', to='pickem.Team'),
        ),
    ]
