# Generated by Django 2.2.4 on 2019-09-18 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pickem', '0003_auto_20190830_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonPickem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('andrew_pick', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='andrew_team', to='pickem.Team')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pickem.Game')),
                ('steve_pick', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steve_team', to='pickem.Team')),
            ],
        ),
    ]
