# Generated by Django 2.2.4 on 2019-09-19 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickem', '0004_seasonpickem'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='abbr',
            field=models.TextField(default=0, max_length=4),
            preserve_default=False,
        ),
    ]
