# Generated by Django 2.2.4 on 2019-09-19 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pickem', '0005_team_abbr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pickem.Game')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pickem.Team')),
            ],
        ),
    ]
