# Generated by Django 2.2.4 on 2019-08-30 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [

    ]
