# Generated by Django 2.2.4 on 2019-10-31 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20191030_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailPrivilege',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.ValidEmail')),
                ('privilege', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.PrivilegeLookup')),
            ],
        ),
    ]
